apiVersion: apps/v1
kind: Deployment
metadata:
  name: some-content-nginx-deployment2
spec:
  selector:
    matchLabels:
      app: some-content-nginx2
  template:
    metadata:
      labels:
        app: some-content-nginx2
    spec:
      containers:
      - name: some-content-nginx2
        image: aniketingale/some-content-nginx:2.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
